# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-11-25 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20181125_1832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Product',
        ),
    ]
